on:
  workflow_run:
    workflows: ["Continuous integration"]
    branches: [main]
    types: 
      - completed

name: Build and Release

env:
  EXECUTABLE_NAME: execd

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build 
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      
      - name: Rename
        run: strip target/release/$EXECUTABLE_NAME && mv target/release/$EXECUTABLE_NAME target/release/$EXECUTABLE_NAME-${{ matrix.target }}
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/$EXECUTABLE_NAME-${{ matrix.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}